### ISSUE TITLE
Sensible default behavior for --ingress arg

### ISSUE THREAD

**Issue by thehunmonkgroup** [yassen-itlabs/py-linux-traffic-control#1]
I'd like to see the usage of the --ingress argument cleaned up a bit -- I think it's requiring too much of the end user, more can be hidden in the default case.

Not sure exactly what's required under the hood, but if the usual use case is only to create ifb0, then the end user shouldn't need to manage that in the setup, it can be done automatically. And if other ifb devices need to be created, then specify them directly. So, eg., '--ingress' alone would create then use ifb0, and '--ingress ifb1' would create and use ifb1, etc.

Open to other approaches, mostly wanting the higher level API to be easier to use in this case.

**Comment by yassen-itlabs** [comment]
Resolved with 67246a3a0857. Tested to some extend, but still some instability is possible. Closing anyway, if anything pops up, please file a bug ticket, thanks!
