### ISSUE TITLE
add profile support to the simnet wrapper

### ISSUE THREAD

**Issue by thehunmonkgroup** [yassen-itlabs/py-linux-traffic-control#16]
enabling something like this:
```python
from pyltc.core.facade import TrafficControl
TrafficControl.init()
simnet = TrafficControl.get_plugin('simnet')
simnet.profile('4g-sym', config_file='/my/config.profile')
simnet.marshal()
```
the config_file argument being optional.

**Comment by yassen-itlabs** [comment]
Implemented. I suggest to name the method `load_profile()` -- a bit more expressive:

```python
simnet.load_profile('4g-sym', config_file='/my/config.profile')
```

The ``config_file`` argument is indeed optional; if not given, the tool will try to load it from default locations specified in ``pyltc/conf.py:CONFIG_PATHS``.

Closing this one.
