### ISSUE TITLE
Add examples to README for using Python modules directly

### ISSUE THREAD

**Issue by thehunmonkgroup** [yassen-itlabs/py-linux-traffic-control#5]
The README only includes examples for command line usage, we also need examples for using the underlying Python modules directly from other Python code.

**Comment by yassen-itlabs** [comment]
Absolutely, I need to clarify a bit the concepts and the design first and will then document this.

**Comment by yassen-itlabs** [comment]
Basic examples provided in the README.rst with 90c2e9669eb6ebbc8fe173fd0cf360a176358f41. I believe it resolves the issue. (Please reopen if you think here's a heavy need of more information.)
